---
- name: Meraki Layer 7 Firewall Configuration
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Set some example Layer 7 firewall rules 
      meraki_mx_l7_firewall:
        org_name: "{{ org_name }}"
        net_name: "{{ net_name }}"
        state: present
        rules:
          - policy: deny
            type: application
            application:
              name: "{{ app_name}}"
      delegate_to: localhost
